linuxdeepin/deepin-system-monitor

- src/process_item.cpp
- src/process_item.h
- src/status_monitor.cpp
This prevents single high-memory-usage application to be list as a
negative number.
> Store memory usage in long instead of int

- deepin-system-monitor-main/system/cpu_set.cpp
- deepin-system-monitor-main/system/cpu_set.h
通过dmidecode读取CPU缓存信息解决lscpu无法正确读取CPU缓存问题
Log: 正确显示CPU缓存信息
/review @pengfeixx
> fix: 系统监视器二级菜单中CPU缓存等信息显示为空

- deepin-system-monitor-main/dbus/systemd1_manager_interface.h
dbus在call时柱塞了GUI信号
Log: 正常关闭应用
Bug: https://pms.uniontech.com/bug-view-152357.html
@lzwind @pengfeixx @feeengli @hundundadi
> fix:  重复开启并快速关闭系统监视器3-4次后应用无法正常启动

- deepin-system-monitor-plugin/dbus/dbusinterface.cpp
开始时SystemMonitorPluginPopup未启动导致连接dbus柱塞，通过多进程方法防止dock柱塞
Log: 开机正常启动系统监视器
Bug: https://pms.uniontech.com/bug-view-149531.html
/review @lzwind @feeengli @myk1343 @hundundadi @jeffshuai
> fix: 开机首次点击任务栏插件区的系统监视器任务栏卡住1min以上功能不可用

- deepin-system-monitor-plugin/dbus/dbusinterface.cpp
社区版本缺少qdbus不能启动插件的问题
Log: 社区版本缺少qdbus不能启动插件的问题
Bug: https://pms.uniontech.com/bug-view-155451.html
/review
@wyu71 @myk1343
> fix: 社区版本缺少qdbus不能启动插件的问题

- deepin-system-monitor-main/gui/system_service_table_view.cpp
只设置系统服务表头不可用
Log: 正常显示系统服务按钮
Bug: https://pms.uniontech.com/bug-view-157227.html
> fix: 系统服务刷新后系统服务按钮出现focus状态

- deepin-system-monitor-main/gui/process_table_view.cpp
- deepin-system-monitor-main/model/process_table_model.cpp
- deepin-system-monitor-main/model/process_table_model.h
增加读取优先级值接口
Log: 正确显示优先级
Bug: https://pms.uniontech.com/bug-view-166309.html
> fix: 系统监视器修改进程优先级后重新查看优先级始终显示为19

- deepin-system-monitor-main/process/desktop_entry_cache_updater.cpp
识别UOS助手启动插件
Log: 正常显示文管图标
Bug: https://pms.uniontech.com/bug-view-160309.html
> fix: 通过统信UOS助手启动文管在系统监视器中进程中图标显示错误

- CMakeLists.txt
- config.h.in
- deepin-system-monitor-main/CMakeLists.txt
- deepin-system-monitor-main/common/common.cpp
- deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp
由于 deepin 的 kwayland 版本与 kde 的新版本不兼容，需要维护禁用 option
> fix: fix option to disable kwayland

- deepin-system-monitor-plugin/CMakeLists.txt
- deepin-system-monitor-plugin/gui/monitor_plugin.h
Log: 使用 cmake 引入 dde-dock, 头文件避免使用绝对路径
之前的 DdeDockInterface_INCLUDE_DIRS 是空值，不生效，现在补充 pkg_check_modules
> chore: avoid use hard path header file

- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
解决缺少符号，导致dock无法加载插件的问题。解决方式为添加了一个空的实现。
> fix: missing symbol of MonitorPlugin::pluginStateSwitched()

- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
安装新Dock接口添加插件图标
Log: 正常显示系统监视器图标
Bug: https://pms.uniontech.com/bug-view-181003.html
> fix: 插件区域下显示无系统监视器图标

- deepin-system-monitor-main/process/desktop_entry_cache_updater.cpp
过滤部分文管的desktop
Log: 正常显示文管图标
Bug: https://pms.uniontech.com/bug-view-160309.html
> fix: 文管在系统监视器中进程中图标显示错误

- .reuse/dep5
- .tx/deepin.conf
- CMakeLists.txt
- deepin-system-monitor-daemon/src/systemmonitorservice.cpp
- deepin-system-monitor-server/CMakeLists.txt
- deepin-system-monitor-server/com.deepin.SystemMonitorServer.service
- deepin-system-monitor-server/src/dbusserver.cpp
- deepin-system-monitor-server/src/dbusserver.h
- deepin-system-monitor-server/src/main.cpp
deepin-server-manager无法启动GUI应用
Log: 正确显示消息通知
Bug: https://pms.uniontech.com/bug-view-194991.html
> fix: 资源占用达到报警阈值时未弹出消息通知

- deepin-system-monitor-main/system/nl_hwaddr.cpp
Log: Add length check before copying device name
> fix: risk function strcpy in nl_hwaddr.cpp

- deepin-system-monitor-main/process/desktop_entry_cache.h
- deepin-system-monitor-main/process/desktop_entry_cache_updater.cpp
微信、QQ、腾讯会议、钉钉、腾讯视频系统监视器，查看进程，会发现图标对不上的问题
Log: 微信、QQ、腾讯会议、钉钉、腾讯视频系统监视器，查看进程，会发现图标对不上的问题
Bug: https://pms.uniontech.com/bug-view-196499.html
> fix: 微信、QQ、腾讯会议、钉钉、腾讯视频系统监视器，查看进程，会发现图标对不上的问题

- deepin-system-monitor-main/system/block_device_info_db.cpp
修复传输文件时，系统监视器不显示传输速度
Log: 修复传输文件时，系统监视器不显示传输速度
Bug: https://pms.uniontech.com/bug-view-200077.html
> fix: 修复传输文件时，系统监视器不显示传输速度

- debian/control
修复1060因deepin-service-manager不启动server
Log: 修复1060因deepin-service-manager不启动server
> fix: 修复1060末启动server

- deepin-system-monitor-main/assets/org.deepin.system-monitor.main.json
Description: 修改默认配置值为-1,存在dconfig接口但是底层未修改配置文件时，将采用以前判断hw的方式
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html
> feat: hw机型判断适配dconfig

- debian/changelog
- deepin-system-monitor-main/dbus/dbus_object.cpp
在dde-dock中右键菜单系统监视器图标无法激活系统监视器窗口到顶层
Log: 修复在dde-dock中右键菜单系统监视器图标无法激活系统监视器窗口到顶层
Bug: https://pms.uniontech.com/bug-view-191373.html
> fix: 修复在dde-dock中右键菜单系统监视器图标无法激活系统监视器窗口到顶层

- debian/control
- deepin-system-monitor-main/CMakeLists.txt
for ltp48h nonghang
Log: for ltp48h nonghang
> feat: for ltp48h nonghang

- deepin-system-monitor-main/common/sample.h
修复火狐浏览器进程的磁盘写入速率达到8EB/s
Log: cancelled_write_bytes时磁盘写入速率达到8EB/s
Bug: https://pms.uniontech.com/bug-view-212249.html
> fix: 火狐浏览器进程的磁盘写入速率达到8EB/s

- CMakeLists.txt
- deepin-system-monitor-main/common/common.cpp
- deepin-system-monitor-main/dbus/dbusalarmnotify.cpp
- deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp
- deepin-system-monitor-main/gui/process_table_view.cpp
- deepin-system-monitor-main/model/accounts_info_model.cpp
- deepin-system-monitor-main/wm/wm_window_list.cpp
- deepin-system-monitor-plugin-popup/dbus/dbusdockinterface.cpp
- deepin-system-monitor-plugin-popup/dbus/dbusdockinterface.h
- deepin-system-monitor-plugin-popup/gui/mainwindow.cpp
- deepin-system-monitor-plugin/CMakeLists.txt
- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
- helper.hpp
It intrudce in the commit 2b8ee33fe9a9b77053cfa81502089f382322cbf2
Refact to distinguish the way of v20 and v23, we delay it
tu runtime step instead of compiling step.
> fix: Can't pack v23 in obs

- helper.hpp
It intrudced in the commit 6e1c14c24b0ec6de1e81807dc7ee531fe2259fda
Missing DBus's assignment of the ObjectPath.
> fix: deepin-system-monitor crashed

- debian/control
- deepin-system-monitor-plugin/CMakeLists.txt
- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
判断dde-dock版本，区分V23与V20插件实现
Log: 判断dde-dock版本，区分V23与V20插件实现
> fix: 判断dde-dock版本，区分V23与V20插件实现

- deepin-system-monitor-plugin/CMakeLists.txt
- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
通过dde-dock版本判断任务栏插件的处理方式
Log: 通过dde-dock版本判断任务栏插件的处理方式
> fix: 通过dde-dock版本判断任务栏插件的处理方式

- deepin-system-monitor-plugin/CMakeLists.txt
- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
通过pluginIsDisable()判断首次安装是否显示，无需应用自己编写配置文件并保存状态
Log: 控制中心任务栏首次设置系统监视器展示，需要点击2次，系统监视器图标才会在任务栏中显示
Bug: https://pms.uniontech.com/bug-view-213941.html
> fix: 控制中心任务栏首次设置系统监视器展示，需要点击2次，系统监视器图标才会在任务栏中显示

- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitorpluginbuttonwidget.cpp
- deepin-system-monitor-plugin/gui/monitorpluginbuttonwidget.h
- deepin-system-monitor-plugin/gui/quickpanelwidget.cpp
> feat: 插件图标更换为系统图标

- deepin-system-monitor-main/3rdparty/displayjack/wayland_client.h
- deepin-system-monitor-main/CMakeLists.txt
- deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp
- deepin-system-monitor-main/gui/xwin_kill_preview_widget.h
Adapt displayjack lib getWindowStatesList() interface
Log: Adapt displayjack lib getWindowStatesList() interface
Bug: https://pms.uniontech.com/bug-view-235483.html
> fix: Adapt displayjack lib getWindowStatesList() interface

- debian/postinst
QT通过platformpluginpath插件对具有cap_sys_ptrace的程序提权为root
Log:  修复对具有cap_sys_ptrace的程序提权为root漏洞
Bug: https://pms.uniontech.com/bug-view-239329.html
> fix: 修复 deepin-system-monitor漏洞

- deepin-system-monitor-main/model/accounts_info_model.cpp
- deepin-system-monitor-main/model/accounts_info_model.h
- deepin-system-monitor-main/process/process_set.cpp
resolve 2 memory lesks
Log: resolve 2 memory leaks
Bug: https://pms.uniontech.com/bug-view-239575.html
> fix: resolve 2 memory leaks

- deepin-system-monitor-main/model/accounts_info_model.cpp
- deepin-system-monitor-main/process/process.cpp
- deepin-system-monitor-plugin-popup/process/process.cpp
1. QList loops to append repeated data;
2. Forgot to release temporary malloc data.
Log: fix two code block memory leaks.
Bug: https://pms.uniontech.com/bug-view-239575.html
> fix: tow code blocks cause memory leak.

- deepin-system-monitor-main/gui/base/base_item_delegate.cpp
- deepin-system-monitor-main/model/process_table_model.cpp
Fix the issue of QPixmapCache running ineffectively
Log: Fix the issue of QPixmapCache running ineffectively
Bug: https://pms.uniontech.com/bug-view-239575.html
> fix: Fix the issue of QPixmapCache running ineffectively

- deepin-system-monitor-plugin-popup/dbus/dbusdockinterface.h
修复任务栏打开系统监视器popup会覆盖在任务栏上
Log:  修复任务栏打开系统监视器popup会覆盖在任务栏上
Bug: https://pms.uniontech.com/bug-view-240273.html
> fix: 修复任务栏打开系统监视器popup会覆盖在任务栏上

- deepin-system-monitor-main/process/process_set.cpp
the app add a blank proc while some apps closed.
Log: the dsm cant delete the closed proc on ui
Bug: https://pms.uniontech.com/bug-view-226579.html
> fix: the app add a blank proc while some apps closed.

- deepin-system-monitor-main/gui/process_table_view.cpp
- deepin-system-monitor-main/process/process_db.cpp
Description: 修复系统监视器中强制结束防杀进程失败后，弹出多次提示窗口的问题
Log: 修修复系统监视器中强制结束防杀进程失败后，弹出多次提示窗口的问题
Bug: https://pms.uniontech.com/bug-view-245061.html
> fix: 修复系统监视器中强制结束防杀进程失败后，弹出多次提示窗口的问题

- deepin-system-monitor-plugin-popup/dbus/systemmonitordbusadaptor.h
- deepin-system-monitor-plugin-popup/gui/mainwindow.cpp
- deepin-system-monitor-plugin-popup/gui/mainwindow.h
- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
适配任务栏图标激活状态，系统监视器打开的时候任务栏图标显示为激活状态
Log: 适配任务栏图标激活状态，系统监视器打开的时候任务栏图标显示为激活状态
Task: https://pms.uniontech.com/task-view-331683.html
> feat: 适配任务栏图标激活状态

- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-plugin/gui/monitor_plugin.h
- deepin-system-monitor-plugin/gui/quickpanelwidget.cpp
暂时屏蔽系统监视器插件，点击动作
改为打开系统监视器主程序
Log: 部分功能调整
Task: https://pms.uniontech.com/story-view-30767.html
> fix: 暂时屏蔽系统监视器插件

- debian/changelog
Bump version to 6.0.18
PR:
* fix: 暂时屏蔽系统监视器插件 (#329)
Log: Bump version to 6.0.18
> chore: Bump version to 6.0.18

- deepin-system-monitor-main/system/sys_info.cpp
- deepin-system-monitor-main/system/sys_info.h
修复平均负载展示的指标值与实际查询的值相一致
Log:  修复平均负载展示的指标值与实际查询的值相一致
Bug: https://pms.uniontech.com/bug-view-250027.html
> fix:  修复平均负载展示的指标值与实际查询的值相一致

- deepin-system-monitor-main/gui/base/base_table_view.cpp
- deepin-system-monitor-main/gui/base/base_table_view.h
- deepin-system-monitor-main/gui/process_page_widget.cpp
- deepin-system-monitor-main/gui/process_page_widget.h
- deepin-system-monitor-main/system/system_monitor.cpp
- deepin-system-monitor-main/system/system_monitor.h
非GUI线程间接调用了update()函数, update()内部的
处理函数会调用markDirty()更新脏控件列表，但是
dirtyWidget(QVector)在多线程访问时可能无法正确
更新数据，导致widget的inDirtyList标识为true，
但dirtyWidget后续未正确的复位标识。
在QWidgetBackingStore::doSync()中一直无法正确的
将绘制数据刷新。
调整onStatInfoUpdated()中的setText()函数到GUI线程。
Log: 修复界面刷新显示问题
Bug: https://pms.uniontech.com/bug-view-247719.html
同时回退之前的临时修改
> fix: 修复非GUI线程调用 update() 函数 

- deepin-system-monitor-plugin/gui/quickpanelwidget.cpp
The font size of the system is set to the largest, and some of the text in the shortcut panel is incomplete.
Log: The quick panel plugin not show correct.
Bug: https://pms.uniontech.com/bug-view-260963.html
> fix: The quick panel plugin not show correct

- debian/deepin-system-monitor.sysusers
- debian/postinst
- debian/rules
- deepin-system-monitor-plugin-popup/com.deepin.SystemMonitorPluginPopup.conf
- deepin-system-monitor-system-server/misc/deepin-system-monitor-system-server.service
- deepin-system-monitor-system-server/misc/org.deepin.SystemMonitorSystemServer.conf
Secure the dbus service
Log: Secure the dbus service
Task: https://pms.uniontech.com/task-view-355357.html
> fix:  Secure the dbus service

- deepin-system-monitor-plugin/gui/monitor_plugin.cpp
- deepin-system-monitor-server/src/dbusserver.cpp
使用am启动deepin-system-monitor
Issue: https://github.com/linuxdeepin/developer-center/issues/9890 https://github.com/linuxdeepin/developer-center/issues/9832
> chore: 使用am启动deepin-system-monitor

- deepin-system-monitor-main/system/cpu_set.cpp
Remove the call to the bash program.
Log: enhance security
Task: https://pms.uniontech.com/task-view-362563.html
> fix: remove the call to the bash program

- deepin-system-monitor-main/system/cpu_set.cpp
压测时观察当前频率”不明显，因取值首个CPU频率有效值
Log: 显示所有 CPU 核中最大的值
Bug: https://pms.uniontech.com/bug-view-277329.html
> fix: “当前频率”显示所有 CPU 核中最大的值

- deepin-system-monitor-main/gui/main_window.cpp
- deepin-system-monitor-main/gui/main_window.h
- deepin-system-monitor-main/gui/process_page_widget.cpp
Previously, when killing an application, system-monitor needed to obtain the pid of the app. However, on a desktop environment using X11, system-monitor obtained an inaccurate pid of the linglong app, which resulted in failure to kill the app or accidental killing. Now consider using the window manager to kill the application, because the window manager contains detailed information about the application window.
Log: fix fail to kill linglong app
Bug: https://pms.uniontech.com/bug-view-283189.html
> fix: fix fail to kill linglong app

- deepin-system-monitor-main/stack_trace.h
> chore: redirect crash log to cache path.

- deepin-system-monitor-daemon/configs/json/org_deepin_system-monitor_daemon.hpp
- deepin-system-monitor-main/configs/json/org_deepin_system-monitor.hpp
- deepin-system-monitor-main/configs/json/org_deepin_system-monitor_main.hpp
- deepin-system-monitor-plugin-popup/configs/json/org_deepin_system-monitor_plugin_popup.hpp
- deepin-system-monitor-plugin/configs/json/org_deepin_system-monitor_plugin.hpp
- deepin-system-monitor-server/configs/json/org_deepin_system-monitor_server.hpp
- Add thread-safe DConfig wrapper classes for all components
- Implement log rules configuration with default settings
- Support configuration change notifications
- Add configuration backends for daemon, main, plugin, plugin-popup and server
Log: add DConfig wrapper classes for system monitor components
> chore: add DConfig wrapper classes for system monitor components

- deepin-system-monitor-daemon/configs/json/org_deepin_system-monitor_daemon.hpp
- deepin-system-monitor-main/configs/json/org_deepin_system-monitor.hpp
- deepin-system-monitor-main/configs/json/org_deepin_system-monitor_main.hpp
- deepin-system-monitor-plugin-popup/configs/json/org_deepin_system-monitor_plugin_popup.hpp
- deepin-system-monitor-plugin/configs/json/org_deepin_system-monitor_plugin.hpp
- deepin-system-monitor-server/configs/json/org_deepin_system-monitor_server.hpp
- Add thread-safe DConfig wrapper classes for all components
- Implement log rules configuration with default settings
- Support configuration change notifications
- Add configuration backends for daemon, main, plugin, plugin-popup and server
Log: add DConfig wrapper classes for system monitor components
> chore: add DConfig wrapper classes for system monitor components (#384)

- deepin-system-monitor-main/gui/main_window.cpp
- Add hide() before sending killWindow dbus message
- Add QTimer to show window after 1 second
- Improve user experience during process killing
Log: improve window behavior when killing process
Bug: https://pms.uniontech.com/bug-view-291531.html
> fix: hide window temporarily when killing process via KWin

- deepin-system-monitor-main/gui/accounts_widget.cpp
- deepin-system-monitor-main/gui/user_page_widget.cpp
- deepin-system-monitor-main/model/accounts_info_model.cpp
- Clean up redundant qCInfo debug logs in accounts related components
- Remove verbose logging in AccountsWidget, UserPageWidget and AccountsInfoModel
Log: remove debug logs in accounts module
Bug: https://pms.uniontech.com/bug-view-298213.html
> fix: remove debug logs in accounts module

- deepin-system-monitor-daemon/src/systemmonitorservice.cpp
- deepin-system-monitor-main/common/common.cpp
- Add fallback mechanism when gdbus call fails
- Add timeout handling for CPU and Memory alarm notifications
- Replace direct command execution with QProcess for better control
Log: improve gdbus call handling for system alarms
Bug: https://pms.uniontech.com/bug-view-283139.html
> fix: improve gdbus call handling for system alarms

- deepin-system-monitor-daemon/src/systemmonitorservice.cpp
- deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp
- Replace QProcess::startDetached with process.start and waitForFinished
- Refactor gdbus command construction using QStringList arguments
- Improve error handling for dbus calls
Log: optimize gdbus call process in system monitor
Bug: https://pms.uniontech.com/bug-view-283139.html
> fix: optimize gdbus call process in system monitor

- deepin-system-monitor-main/gui/main_window.cpp
- Add delay before sending kill window dbus message
- Improve window hide/show timing sequence
- Enhance window state management during kill operation
Log: optimize window kill process in KDE environment
Bug: https://pms.uniontech.com/bug-view-291531.html
> fix: optimize window kill process in KDE environment

- deepin-system-monitor-main/process/desktop_entry_cache.h
- deepin-system-monitor-main/process/desktop_entry_cache_updater.cpp
Add special handling for linglong applications by parsing ll-cli output to get app info
Log: add linglong app support in desktop entry cache updater
Bug: https://pms.uniontech.com/bug-view-279859.html
https://pms.uniontech.com/bug-view-284207.html
https://pms.uniontech.com/bug-view-304217.html
https://pms.uniontech.com/bug-view-306483.html
> fix: add linglong app support in desktop entry cache updater

- deepin-system-monitor-plugin/gui/monitorpluginbuttonwidget.cpp
Updated the pixmap size calculation to use the original size instead of adjusting for high DPI settings. This change ensures that the icon is rendered at the intended size without scaling issues.
bug：https://pms.uniontech.com/bug-view-313925.html
> fix: Adjust pixmap size calculation in MonitorPluginButtonWidget

- deepin-system-monitor-plugin/gui/commoniconbutton.cpp
- Introduced a constant `ICON_SIZE` for the icon dimensions to improve code readability and maintainability.
- Updated the fixed size and pixmap drawing to utilize this constant, ensuring consistency across the component.
This change enhances the clarity of the code and makes future adjustments to the icon size easier.
> fix: Use constant for icon size in CommonIconButton

- deepin-system-monitor-main/gui/process_attribute_dialog.cpp
- Disabled vertical scrollbar for process start time text widget to improve UI consistency
- Added conditional check to prevent unwanted text selection clearing on viewport interaction
Log: remove unnecessary scrollbar from process start time field
pms: BUG-325687
> fix: remove unnecessary scrollbar from process start time field
