linuxdeepin/deepin-system-monitor

src/common/logger.hpp
src/compact_memory_monitor.cpp
src/cpu_monitor.h
src/gui/base_header_view.cpp
src/memory_monitor.cpp
src/process/desktop_entry_stat.cpp
src/process/process_stat.cpp
src/process/system_stat.cpp
src/utils.cpp

Fixes linuxdeepin#40 linuxdeepin#47 linuxdeepin#48
Log:
Issue: Fixes linuxdeepin#40 linuxdeepin#47 linuxdeepin#48

fix: multiple definition

---

deepin-system-monitor-plugin-popup/deepin-system-monitor-plugin-popup.desktop

NoShowIn -> NotShowIn
Log: NoShowIn -> NotShowIn

fix: NoShowIn -> NotShowIn

---

deepin-system-monitor-plugin-popup/gui/mainwindow.cpp
deepin-system-monitor-plugin-popup/gui/mainwindow.h

popup进程不再常驻，5分钟闲置后退出
Log: popup进程不再常驻，5分钟闲置后退出

feat: popup进程不再常驻，5分钟闲置后退出

---

deepin-system-monitor-main/system/block_device_info_db.cpp

修改实体磁盘和虚拟磁盘顺序
Log: 修改实体磁盘和虚拟磁盘顺序
Bug: https://pms.uniontech.com/bug-view-146549.html
/review
@wyu71

fix: 修改实体磁盘和虚拟磁盘顺序

---

CMakeLists.txt
debian/changelog
deepin-system-monitor-daemon/systemmonitorservice.cpp
tests/test-prj-running.sh

修改系统监视器面板不能打开的问题
Log: 修改系统监视器面板不能打开的问题
/review
@wyu71 @pengfeixx @HeeMingYang

fix: 修改系统监视器面板不能打开的问题

---

deepin-system-monitor-main/CMakeLists.txt
deepin-system-monitor-main/common/eventlogutils.cpp
deepin-system-monitor-main/common/eventlogutils.h
deepin-system-monitor-main/gui/main_window.cpp

feat: 数据埋点

---

deepin-system-monitor-main/CMakeLists.txt
deepin-system-monitor-main/common/common.cpp
deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp
deepin-system-monitor-main/gui/xwin_kill_preview_widget.h

fix:  linuxdeepin/developer-center#2239
Log: Add build flag to disable wayland support

feat: Add build option to disable wayland support

---

debian/control

chore: update homepage

---

deepin-system-monitor-daemon/systemmonitorservice.cpp

dde的Notification参数错误
Log: 正确启动系统监视器
/review @lzwind @HeeMingYang @feeengli @hundundadi @myk1343

fix: 当CPU或内存占用过高时无法点击通知查看系统监视器

---

deepin-system-monitor-main/cpu_monitor.cpp
deepin-system-monitor-main/gui/process_page_widget.cpp
deepin-system-monitor-main/memory_monitor.cpp
deepin-system-monitor-main/memory_monitor.h
deepin-system-monitor-main/network_monitor.cpp

调整应用程序界面边距
Log: 正确显示应用程序界面边距
Bug: https://pms.uniontech.com/bug-view-157227.html

fix: 应用程序界面边距问题

---

deepin-system-monitor-main/gui/block_dev_item_widget.cpp
deepin-system-monitor-main/gui/chart_view_widget.cpp
deepin-system-monitor-main/gui/cpu_detail_widget.cpp
deepin-system-monitor-main/gui/netif_item_view_widget.cpp

调整CPU磁盘网络界面文字和间距
Log: 正确显示CPU磁盘网络界面文字和间距
Bug: https://pms.uniontech.com/bug-view-157227.html

fix: CPU磁盘网络界面文字和间距

---

deepin-system-monitor-main/gui/process_page_widget.cpp
deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp

点击后不执行F1操作
Log: 强制结束应用程序功能正常
Bug: https://pms.uniontech.com/bug-view-163629.html

fix: 强制结束应用程序在点击的时候同时键盘按下F1后ESC无法退出且界面无法操作

---

deepin-system-monitor-main/system/block_device_info_db.cpp

去掉RAM显示
Log: 隐藏RAM
Bug: https://pms.uniontech.com/bug-view-158671.html

fix: 系统监视器查看磁盘详细信息磁盘名称和占用显示异常

---

deepin-system-monitor-daemon/systemmonitorservice.cpp
deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp
deepin-system-monitor-plugin/gui/monitor_plugin.cpp

修改社区版qdbus未安装无法使用dbus问题
Log: 修改社区版qdbus未安装无法使用dbus问题
Bug: https://pms.uniontech.com/bug-view-156091.html
/review
@pengfeixx @feeengli @myk1343 @HeeMingYang @wyu71

fix: 修改社区版qdbus未安装无法使用dbus问题

---

deepin-system-monitor-main/gui/process_page_widget.cpp

fix: 应用数量与表格不一致

---

deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp

重新计算多屏缩放后大小位置
Log: 正确显示
Bug: https://pms.uniontech.com/bug-view-164735.html

fix: 双屏菜单强制结束应用程序屏幕显示异常

---

deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp

fix: 强制关闭应用时延迟截屏

---

deepin-system-monitor-main/system/netif_packet_capture.cpp

多网卡时未选择默认网卡
Log: 正常显示应用网速
Bug: https://pms.uniontech.com/bug-view-163621.html

fix: 进程列表中上传下载列数据始终为0

---

deepin-system-monitor-main/gui/process_table_view.cpp

fix: 系统监视器的进程自定义优先级数值失败

---

deepin-system-monitor-plugin-popup/gui/mainwindow.cpp

fix: 开启启动popup程序无法自动退出

---

deepin-system-monitor-plugin/gui/monitorpluginbuttonwidget.cpp

fix: 任务栏图标模糊问题

---

deepin-system-monitor-plugin/gui/monitor_plugin.cpp

任务栏插件默认不显示
Log: 任务栏插件默认不显示
Task: https://pms.uniontech.com/task-view-223319.html

feat: 任务栏插件默认不显示

---

deepin-system-monitor-main/service/service_manager.cpp

修复了非开发者模式无法修改服务启动方式
Log: 正确修改服务启动方式

fix: 非开发者模式下无法修改服务启动方式

---

debian/control
deepin-system-monitor-main/CMakeLists.txt
deepin-system-monitor-main/common/common.cpp
deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp
deepin-system-monitor-main/gui/xwin_kill_preview_widget.h
deepin-system-monitor-main/wm/wm_window_list.cpp
deepin-system-monitor-plugin/gui/monitor_plugin.cpp
deepin-system-monitor-plugin/gui/monitor_plugin.h

wayland下系统监视器打不开和去掉插件是否可用
Log: wayland下系统监视器打不开

fix: wayland下系统监视器打不开和去掉插件是否可用

---

.tx/deepin.conf
debian/changelog

chore: 更新版本6.0.3

---

deepin-system-monitor-main/system/cpu_set.cpp

fix: 更新类型判断

---

deepin-system-monitor-daemon/systemmonitorservice.cpp
deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp
deepin-system-monitor-main/wm/wm_window_list.cpp
deepin-system-monitor-plugin-popup/dbus/dbusdockinterface.cpp
deepin-system-monitor-plugin-popup/dbus/dbusdockinterface.h
deepin-system-monitor-plugin-popup/gui/mainwindow.cpp

fix: 调整dbus接口

---

deepin-system-monitor-plugin-popup/gui/mainwindow.cpp

fix: 更新popup的dbus

---

debian/control
deepin-system-monitor-plugin-popup/CMakeLists.txt
deepin-system-monitor-plugin-popup/gui/mainwindow.cpp
deepin-system-monitor-plugin-popup/gui/mainwindow.h
deepin-system-monitor-plugin/CMakeLists.txt

fix: 使用新的dbus接口

---

deepin-system-monitor-main/gui/process_table_view.cpp

通过进程里的mountinfo和exe文件拼接完整目录
Log: 正确调整目录
Bug: https://pms.uniontech.com/bug-view-183667.html

fix: 开启浏览器并在系统监视器中选择查看命令所在位置时跳转目录错误

---

debian/changelog
deepin-system-monitor-daemon/CMakeLists.txt
deepin-system-monitor-main/CMakeLists.txt
deepin-system-monitor-plugin-popup/CMakeLists.txt

update version
Log: update version

chore: update version

---

deepin-system-monitor-main/3rdparty/lscpu-topology.c
deepin-system-monitor-main/gui/cpu_summary_view_widget.h

修改了部分机型cpu的modelname为空时cpu信息错误
Log: cpu信息正常

fix: 部分机型cpu的modelname为空时cpu信息错误

---

debian/changelog

chore: 更新版本6.0.6

---

deepin-system-monitor-main/common/eventlogutils.h
deepin-system-monitor-main/gui/process_page_widget.cpp
deepin-system-monitor-main/gui/process_table_view.cpp
deepin-system-monitor-main/gui/process_table_view.h

添加进程结束数据上报
Log: 添加进程结束数据上报
Task: https://pms.uniontech.com/task-view-250733.html

fix: 添加进程结束数据上报

---

debian/control

chore: 添加服务依赖

---

deepin-system-monitor-plugin/gui/monitor_plugin.cpp

https://github.com/linuxdeepin/developer-center/issues/3747
Log: 修改图标大小

fix: Modify taskbar icon size

---

deepin-system-monitor-main/common/eventlogutils.h
deepin-system-monitor-main/gui/process_page_widget.cpp
deepin-system-monitor-main/gui/process_table_view.cpp
deepin-system-monitor-main/gui/process_table_view.h

fix: 同步 进程结束数据上报 代码

---

.tx/deepin.conf
debian/changelog

chore: 更新版本5.9.33

---

deepin-system-monitor-main/system/cpu_set.cpp

Description: 增加hw新机型W585判断
Log: 增加hw新机型W585判断

chore: 增加hw新机型W585判断

---

debian/changelog

update version 6.0.7
Log: update version 6.0.7

chore: update version 6.0.7

---

debian/changelog
debian/control
debian/deepin-system-monitor-plugin.install
debian/deepin-system-monitor.install

Graded control
Log: Graded control

fix: Graded control

---

debian/changelog
debian/control

Graded control config Replaces and Conflicts
Log: Graded control config Replaces and Conflicts

fix: Graded control config Replaces and Conflicts

---

debian/changelog

update version  5.10.2
Log: update version  5.10.2

chore: update version 5.10.2

---

deepin-system-monitor-main/system/cpu_set.cpp

feat: 新增pgw判断

---

deepin-system-monitor-main/CMakeLists.txt
deepin-system-monitor-main/assets/org.deepin.system-monitor.main.json
deepin-system-monitor-main/common/common.cpp
deepin-system-monitor-main/common/common.h
deepin-system-monitor-main/gui/main_window.cpp
deepin-system-monitor-main/system/cpu_set.cpp

Description: hw机型判断适配dconfig
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html

feat: hw机型判断适配dconfig

---

debian/changelog
debian/deepin-system-monitor.install

dbus开启系统监视器开关
Bug: https://pms.uniontech.com/bug-view-211897.html
Log: dbus开启系统监视器开关

fix: dbus开启系统监视器开关

---

deepin-system-monitor-main/compact_memory_monitor.cpp
deepin-system-monitor-main/cpu_monitor.cpp
deepin-system-monitor-main/gui/animation_stackedwidget.cpp
deepin-system-monitor-main/gui/animation_stackedwidget.h
deepin-system-monitor-main/memory_monitor.cpp
deepin-system-monitor-main/process/process.cpp
deepin-system-monitor-main/process/process.h
deepin-system-monitor-main/process/process_set.cpp
deepin-system-monitor-main/process/process_set.h
deepin-system-monitor-main/system/sys_info.cpp
deepin-system-monitor-main/system/sys_info.h
deepin-system-monitor-main/system/system_monitor.cpp
deepin-system-monitor-plugin-popup/process/process.cpp
deepin-system-monitor-plugin-popup/process/process.h

系统监视器占用资源过高优化
Log: 系统监视器占用资源过高优化

fix: 系统监视器占用资源过高优化

---

debian/control

fix: 插件功能回退

---

deepin-system-monitor-main/process/process.h
deepin-system-monitor-main/process/process_set.cpp
deepin-system-monitor-main/process/process_set.h

feat: 优化底层数据读取

---

debian/changelog

bump version  5.10.5
Log: bump version  5.10.5

chore: bump version 5.10.5

---

debian/changelog

chore: Update changelog to 6.0.8

---

deepin-system-monitor-plugin/gui/monitor_plugin.cpp
deepin-system-monitor-plugin/gui/monitor_plugin.h
deepin-system-monitor-plugin/gui/quickpanelwidget.cpp
deepin-system-monitor-plugin/gui/quickpanelwidget.h

快捷面板启动应用系统监示器后快捷面板自动隐藏
Log: quickpannel start app and disappeared self auto
Bug: https://pms.uniontech.com/bug-view-228255.html
Bug: https://pms.uniontech.com/bug-view-228257.html

fix: quickpannel start app and disappeared self auto

---

debian/changelog

chore: bump version 6.0.9

---

debian/changelog

chore: tag 6.0.10

---

deepin-system-monitor-main/system/cpu_set.cpp

adapt to new models
Log: adapt to new models

feat: adapt to new models

---

debian/changelog

chore: tag 6.0.11

---

debian/changelog

chore: bump version 5.9.39

---

debian/changelog

chore: tag 5.9.40

---

deepin-system-monitor-main/process/process_set.cpp

Fix the issue of m900 getting stuck
Log: Fix the issue of m900 getting stuck
Bug: https://pms.uniontech.com/bug-view-236279.html

fix: Fix the issue of m900 getting stuck

---

debian/changelog

chore: tag 6.0.13

---

deepin-system-monitor-plugin/gui/quickpanelwidget.cpp

快捷面板tips交互优化
Log: 快捷面板tips交互优化
Bug: https://pms.uniontech.com/bug-view-243721.html

fix: 快捷面板tips交互优化

---

debian/changelog

chore: bump version 6.0.16

---

deepin-system-monitor-plugin/gui/monitor_plugin.cpp
deepin-system-monitor-plugin/gui/monitor_plugin.h
deepin-system-monitor-plugin/gui/systemmonitortipswidget.cpp
deepin-system-monitor-plugin/gui/systemmonitortipswidget.h

fix: 插件里延迟读取系统信息

---

deepin-system-monitor-plugin-popup/gui/datadealsingleton.cpp
deepin-system-monitor-plugin-popup/gui/datadealsingleton.h

launch deepin-system-monitor by AM for v23
Log: launch deepin-system-monitor by AM for v23
Influence: launch deepin-system-monitor by AM

feat: launch deepin-system-monitor by AM for v23

---

deepin-system-monitor-main/gui/base/base_table_view.cpp
deepin-system-monitor-main/gui/base/base_table_view.h

使用延时强制刷新替换更新，期望避免
异常的刷新状态
Log: 修复部分显示问题
Bug: https://pms.uniontech.com/bug-view-247719.html

fix: Froce repaint replace update

---

deepin-system-monitor-main/gui/base/base_table_view.cpp
deepin-system-monitor-main/gui/base/base_table_view.h

修复强制刷新占用率过高问题
Log: 修复强制刷新占用率过高问题

fix: 修复强制刷新占用率过高问题

---

deepin-system-monitor-main/system/cpu_set.cpp

旧版CPU当前频率=总CPU使用率*最大核心CPU频率
但在部分CPU下最大频率不同(大小核),导致计算存在差异,
调整当前频率计算方式,取首个CPU当前频率,
和 util-linux 2.33.1.20-1+dde 版本lscpu一致.
Log: 修复部分数据显示问题
Bug: https://pms.uniontech.com/bug-view-253555.html

fix: 调整当前CPU频率获取方式

---

deepin-system-monitor-main/process/desktop_entry_cache.cpp
deepin-system-monitor-main/process/desktop_entry_cache.h
deepin-system-monitor-main/process/process_icon.cpp
deepin-system-monitor-main/process/process_icon.h

系统监视器文件管理器进程图标显示错误
Log: 系统监视器文件管理器进程图标显示错误
Bug: https://pms.uniontech.com/bug-view-257355.html

fix: 系统监视器文件管理器进程图标显示错误

---

debian/changelog

chore: bump version 6.0.20

---

debian/changelog

chore: bump version 6.0.21

---

assets/logconfig/org.deepin.system-monitor.json

ddlog adaptation
Log: ddlog adaptation config

 feat: ddlog adaptation config

---

debian/changelog

chore: bump version 6.0.22

---

debian/changelog

chore: bump version 6.0.23

---

deepin-system-monitor-plugin/CMakeLists.txt

Issues: linuxdeepin/developer-center#9874

fix: missing icon in DCC

---

deepin-system-monitor-main/3rdparty/include/closestream.h
deepin-system-monitor-main/common/common.h
deepin-system-monitor-main/dbus/dbusalarmnotify.cpp
deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp
deepin-system-monitor-main/service/service_manager.cpp
deepin-system-monitor-main/system/netif_packet_capture.cpp
helper.hpp

due to app_error list
Log:  modify "error,fail" to unsucess in logdata

fix:   unvail "error" log output

---

assets/configs/org.deepin.system-monitor.json
deepin-system-monitor-main/gui/process_table_view.cpp

通过dconfig屏蔽进程暂停与恢复进程功能
Bug: https://pms.uniontech.com/bug-view-272331.html
Log: 通过dconfig屏蔽进程暂停与恢复进程功能

fix: 通过dconfig屏蔽进程暂停与恢复进程功能

---

debian/changelog
deepin-system-monitor-main/system/cpu_set.cpp
deepin-system-monitor-system-server/src/systemdbusserver.cpp

Fix some security issues.
Log: fix some security issues
Task: https://pms.uniontech.com/task-view-362563.html

fix: some security issues

---

debian/changelog

Update version to 6.5.2
Log: Update version to 6.5.2

chore: Update version to 6.5.2

---

debian/changelog
deepin-system-monitor-main/common/common.cpp

remove kwayland-shell env
Log: remove kwayland-shell env

fix: remove kwayland-shell env

---

debian/postinst

cancel cap_dac_read_search
Log:  cancel cap_dac_read_search
Bug: https://pms.uniontech.com/task-view-365257.html

fix: [security] cancel cap_dac_read_search

---

debian/changelog

chore: bump version 6.5.4

---

deepin-system-monitor-main/CMakeLists.txt

disable USE_DEEPIN_WAYLAND
Log: to fix 104x compilation issue
Bug: no

fix: to fix 104x compilation issue

---

deepin-system-monitor-main/gui/block_dev_summary_view_widget.cpp

hide the model name
Log: hide the model name
Bug: https://pms.uniontech.com/bug-view-298121.html

fix: hide the model name

---

debian/changelog

New version 6.5.5
Log: New version 6.5.5

chore: New version 6.5.5

---

debian/changelog

Bump version to 6.5.7
Log: Bump version to 6.5.7

chore: Bump version to 6.5.7

---

CMakeLists.txt
deepin-system-monitor-plugin-popup/CMakeLists.txt
deepin-system-monitor-plugin-popup/gui/mainwindow.h
deepin-system-monitor-plugin-popup/main.cpp
deepin-system-monitor-plugin/CMakeLists.txt

fix: [system-monitor] remove dde-dock plugin

---

deepin-system-monitor-main/stack_trace.h

Log: as above.
Bug: https://pms.uniontech.com/bug-view-304245.html

fix: relaunch app if exception was catched

---

deepin-system-monitor-plugin/gui/quickpanelwidget.cpp

- Update layout spacing from 8px to 10px in QuickPanelWidget
- Add Hebrew translation for service startup policy
- Remove Qt5 compatibility code for margins
Log: adjust layout spacing and add Hebrew translation
Bug: https://pms.uniontech.com/bug-view-271223.html

fix: adjust layout spacing and add Hebrew translation

---

debian/changelog

Bump version to 6.5.9
Log: Bump version to 6.5.9

chore: Bump version to 6.5.9

---

debian/changelog

Bump version to 6.5.12
Log: Bump version to 6.5.12

chore: Bump version to 6.5.12

---

deepin-system-monitor-plugin/gui/monitorpluginbuttonwidget.cpp

- Replaced the custom loadSvg function with Qt's built-in icon system for better DPI handling and to avoid scaling issues.
- This change ensures correct icon display across different DPI settings and improves code maintainability.
- Centered icon drawing position is also adjusted to use integer coordinates to prevent precision issues.
bug：https://pms.uniontech.com/bug-view-313925.html
https://pms.uniontech.com/bug-view-314505.html

fix: Simplify icon loading in MonitorPluginButtonWidget

---

debian/changelog

- Update version to 6.5.13.
Log: Bump version to 6.5.13

chore: Bump version to 6.5.13

---

.gitignore
deepin-system-monitor-daemon/src/cpuprofile.cpp
deepin-system-monitor-daemon/src/memoryprofile.cpp
deepin-system-monitor-daemon/src/settinghandler.cpp
deepin-system-monitor-daemon/src/systemmonitorservice.cpp
deepin-system-monitor-main/common/common.cpp
deepin-system-monitor-main/common/han_latin.cpp
deepin-system-monitor-main/dbus/dbus_object.cpp
deepin-system-monitor-main/dbus/dbusalarmnotify.cpp
deepin-system-monitor-main/dbus/systemd1_service_interface.cpp
deepin-system-monitor-main/dbus/systemd1_unit_interface.cpp
deepin-system-monitor-main/gui/accounts_widget.cpp
deepin-system-monitor-main/gui/animation_stackedwidget.cpp
deepin-system-monitor-main/gui/base/base_detail_view_widget.cpp
deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp
deepin-system-monitor-main/gui/main_window.cpp
deepin-system-monitor-main/gui/process_table_view.cpp
deepin-system-monitor-main/gui/system_service_table_view.cpp
deepin-system-monitor-main/gui/xwin_kill_preview_widget.cpp

- Added detailed debug and warning logs in various components to improve traceability and error handling.
- Introduced new entries in .gitignore for cursor indexing and specification story files to streamline the development process.
Log: Enhance logging

 feat: Enhance logging

---

deepin-system-monitor-plugin-popup/gui/memory_widget.cpp
deepin-system-monitor-plugin-popup/gui/process_table_view.cpp
deepin-system-monitor-plugin-popup/logger.cpp
deepin-system-monitor-plugin-popup/main.cpp
deepin-system-monitor-plugin-popup/process/process.cpp
deepin-system-monitor-plugin-popup/process/process_db.cpp
deepin-system-monitor-system-server/src/systemdbusserver.cpp

- Updated logging statements across various components to provide more detailed debug and warning messages, improving error handling and traceability.
- Added checks and logs for configuration changes, process management, and DBus interactions to facilitate better monitoring and debugging.
Log: Improve logging for enhanced traceability

feat: Enhance logging for better debugging and traceability

---

.clang-format
.gitignore
.reuse/dep5
deepin-system-monitor-main/system/cpu_set.cpp
deepin-system-monitor-main/system/cpu_set.h

- **chore: update .gitignore and add .clang-format file**
- **fix: query cpu cache from lscpu command**

修复系统监视器在一些设备上 cpu 缓存信息与 lscpu 不一致的问题

---

deepin-system-monitor-daemon/src/cpuprofile.cpp
deepin-system-monitor-daemon/src/logger.cpp
deepin-system-monitor-daemon/src/memoryprofile.cpp
deepin-system-monitor-daemon/src/plugin.cpp
deepin-system-monitor-daemon/src/settinghandler.cpp
deepin-system-monitor-daemon/src/systemmonitorservice.cpp
deepin-system-monitor-server/src/dbusserver.cpp
deepin-system-monitor-server/src/logger.cpp
deepin-system-monitor-server/src/main.cpp
deepin-system-monitor-system-server/src/logger.cpp
deepin-system-monitor-system-server/src/main.cpp
deepin-system-monitor-system-server/src/systemdbusserver.cpp

Add more logs for backend.
Log: More logs for backend.

chore: More logs for backend

---

deepin-system-monitor-main/application.cpp
deepin-system-monitor-main/common/common.cpp
deepin-system-monitor-main/common/error_context.cpp
deepin-system-monitor-main/common/eventlogutils.cpp
deepin-system-monitor-main/common/han_latin.cpp
deepin-system-monitor-main/common/hash.cpp
deepin-system-monitor-main/common/perf.cpp
deepin-system-monitor-main/common/thread_manager.cpp
deepin-system-monitor-main/common/time_period.cpp
deepin-system-monitor-main/compact_cpu_monitor.cpp
deepin-system-monitor-main/compact_disk_monitor.cpp
deepin-system-monitor-main/compact_memory_monitor.cpp
deepin-system-monitor-main/compact_network_monitor.cpp
deepin-system-monitor-main/cpu_monitor.cpp
deepin-system-monitor-main/detailwidgetmanager.cpp
deepin-system-monitor-main/logger.cpp
deepin-system-monitor-main/main.cpp
deepin-system-monitor-main/memory_monitor.cpp
deepin-system-monitor-main/network_monitor.cpp
deepin-system-monitor-main/settings.cpp
deepin-system-monitor-main/smooth_curve_generator.cpp

Add more logs for main application.
Log: More logs for main application.

chore: More logs for main application.

---

deepin-system-monitor-main/gui/dialog/systemprotectionsetting.cpp

- Updated string concatenation to use .arg() for better readability and performance.
- Added error handling for DDE control center DBus method calls to improve robustness.
Log: Corrected string formatting and enhanced error handling in system protection settings.

fix: Corrected string formatting in system protection settings

---

debian/changelog

- Updated to version 6.5.25
Log: New version 6.5.25

chore: New version 6.5.25

---

debian/changelog

- Updated to version 6.5.26
Log: New version 6.5.26

chore: New version 6.5.26

---

debian/changelog
deepin-system-monitor-main/translations/deepin-system-monitor_lo.ts
deepin-system-monitor-main/translations/desktop/desktop_lo.ts
deepin-system-monitor-main/translations/policy/policy_lo.ts
deepin-system-monitor-plugin-popup/translations/deepin-system-monitor-plugin-popup_lo.ts
deepin-system-monitor-plugin/translations/deepin-system-monitor-plugin_lo.ts

chore: Add new Lao translation file
Log: Improve language support by adding Lao translation

  chore: Add new Lao translation file     

---

debian/changelog
deepin-system-monitor-main/translations/policy/com.deepin.pkexec.deepin-system-monitor.policy
deepin-system-monitor-main/translations/policy/policy_lo.ts
deepin-system-monitor-system-server/misc/org.deepin.deepin-system-monitor-system-server.policy
deepin-system-monitor-system-server/translations/policy/policy_lo.ts

chore: Add Lao language translations in policy files

chore: Add Lao language translations in policy files 

---

debian/changelog

- update version to 6.0.24
lop: update tag

chore: new tag 6.0.24
